import matplotlib.pyplot as plt
import numpy as np

if __name__ == "__main__":

    data = np.load('constraint-pi-4/VAE/path-PRM-0-samples.npy', allow_pickle=True)

    plt.scatter(data[:, 0], data[:, 1], c='red')

    plt.title('Nodes Generated by VAE (Hidden: {}, Latent: {})'.format(14,10))
    plt.grid()
    plt.show()